version: '2'
services:
  search:
    build: .
    image: mantiser/search
    volumes:
      - ./:/code
    command: tail -f /etc/fstab
    ports:
      - 8080:8080
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
    depends_on: 
      - nats
      - natsout
  natsout:
    build: .
    command: python3 -u fromNats.py
    environment:
      NATS: nats
    depends_on: 
      - nats
  nats:
    image: nats

