FROM ubuntu:18.04

EXPOSE 8080


RUN apt-get update && apt-get install -y python3 python3-pip python3-dev git zlib1g-dev libjpeg-dev libffi-dev telnet curl vim

RUN mkdir /code
RUN mkdir /files
COPY . /code/
WORKDIR /code
RUN pip3 install -r requirements.txt

#Setup gcloud and helm settings
WORKDIR /opt

RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-240.0.0-linux-x86_64.tar.gz
RUN tar zxvf google-cloud-sdk-240.0.0-linux-x86_64.tar.gz
RUN ln -s /opt/google-cloud-sdk/bin/* /usr/sbin/

RUN curl -O  https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
RUN tar zxvf helm-v2.13.1-linux-amd64.tar.gz

RUN ln -s /opt/linux-amd64/helm /usr/sbin/helm


WORKDIR /code
CMD ["python3","-u","deployer.py"]