version: '2'
services:
  search:
    build: .
    volumes:
      - ./:/code
    #command: tail -f /etc/fstab
    ports:
      - 8080:8080
    environment:
      SEARCH: "mantier"
      NATS: nats
    depends_on: 
      - nats
  nats:
    image: nats

