version: '2'
services:
  search:
    build: .
    image: mantiser/search
    volumes:
      - ./:/code
    #command: tail -f /etc/fstab
    ports:
      - 8088:8080
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
      API_KEY: "AIzaSyD8svOCx318Wk1NsUhxtDRv-KRNZtDDbHQ"
      CSE_ID: "012631876750147547556:j4ufbjipbdi"
      PYTHONUNBUFFERED: 1
    networks:
      - mantiser
  natsout:
    build: .
    command: tail -f /etc/fstab
    volumes:
      - ./:/code
    environment:
      NATS: nats
    networks:
      - mantiser
networks:
  mantiser:
    external: true

  

  

