version: '2'
services:
  search:
    build: .
    image: mantiser/search
    volumes:
      - ./:/code
    #command: tail -f /etc/fstab
    ports:
      - 8088:8080
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
      API_KEY: "AIzaSyD8svOCx318Wk1NsUhxtDRv-KRNZtDDbHQ"
      CSE_ID: "012631876750147547556:j4ufbjipbdi"

    depends_on: 
      - nats
      - natsout
  natsout:
    build: .
    command: python3 -u fromNats.py
    environment:
      NATS: nats
    depends_on: 
      - nats
  nats:
    image: nats

