version: '2'
services:
  finder:
    build: .
    volumes:
      - ./:/code
    command: tail -f /etc/fstab
    ports:
      - 8080:8080
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/key/nortamlin_function_localy.json
