version: '2'
services:
  search:
    build: .
    volumes:
      - ./:/code
    command: tail -f /etc/fstab
    ports:
      - 8080:8080
    environment:
      SEARCH: "mattias"
      NATS: nats
  nats:
    image: nats

