#Mantiser search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mantiser-com/user_id: "1112"
  name: api
  labels:
    app: mantiser-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mantiser-api
  template:
    metadata:
      annotations:
        app: mantiser-api
      labels:
        app: mantiser-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: mantiser 
                  key: API_KEY
                  optional: false
            - name: CSE_ID
              valueFrom:
                secretKeyRef:
                  name: mantiser 
                  key: CSE_ID
                  optional: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mantiser-api
  name: api
  namespace: mantiser
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mantiser-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: search
  name: search
  namespace: mantiser
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mantiser-api
  sessionAffinity: None
  type: ClusterIP

