apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantiser-search
spec:
  selector:
    matchLabels:
      app: mantiser-search
  template:
    metadata:
      labels:
        app: mantiser-search
    spec:
      containers:
        - image: mantiser/search
          name: mantiser-search
          imagePullPolicy: Never
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "site:arbetsformedlingen.se devops"
            - name: USER_ID
              value: "useridasdasdasdasd"
            - name: SCANNER_ID
              value: "scannerid233333"
            - name: SCANNER_INFO
              value: '{"dummy":"data"}'
            - name: RESULT_NATS
              value: "nats"
          #command: ['python','-u','/code/service_watch.py']        

---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
  - port: 8080
    name: flask
    targetPort: 8080
  selector:
    app: mantiser-search
  type: LoadBalancer
